In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,PReLU
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import numpy as np
from matplotlib import image
import pickle

In [37]:
model = Sequential()
model.add(Conv2D(128, (3,3), padding='same', input_shape = (28, 28, 4), kernel_initializer="he_normal"))
model.add(PReLU())
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(128, (3,3), padding='same', kernel_initializer="he_normal"))
model.add(PReLU())
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(128, (3,3), padding='same', kernel_initializer="he_normal"))
model.add(PReLU())
model.add(MaxPooling2D((2, 2)))

model.add(Flatten())
model.add(Dense(10,activation = 'softmax'))
model.summary()
#number of layers, number of kernels, epochs

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 28, 28, 128)       4736      
_________________________________________________________________
p_re_lu_2 (PReLU)            (None, 28, 28, 128)       100352    
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 128)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 14, 14, 128)       147584    
_________________________________________________________________
p_re_lu_3 (PReLU)            (None, 14, 14, 128)       25088     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 7, 7, 128)         0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 7, 7, 128)        

In [3]:
import pandas as pd
train = pd.read_csv("train.csv")
train.head()

filename  label
0    0.png      4
1    1.png      9
2    2.png      1
3    3.png      7
4    4.png      3

In [4]:
train.shape

(49000, 2)

In [5]:
image.imread("Images/train/0.png")

array([[[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       ...,

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0.

In [6]:
# Uncomment to load train images from train.csv. This takes some time instead use X,y pickle files
#X = []
#y = []
#for i,j in zip(train.filename, train.label):
#    X.append(image.imread("Images/train/"+i))
#    y.append(j)
#print(len(X), len(y))

In [7]:
# Uncomment to save X and y Data
#f1 = open("X.pickle", "wb")
#f2 = open("y.pickle", "wb")
#pickle.dump(X,f1)
#pickle.dump(y,f2)
#f1.close()
#f2.close()

In [8]:
f1 = open("X.pickle", "rb")
f2 = open("y.pickle", "rb")
X = pickle.load(f1)
y = pickle.load(f2)

In [9]:
X[0].shape

(28, 28, 4)

In [10]:
X = np.array(X)
y = np.array(y)

In [11]:
X.shape

(49000, 28, 28, 4)

In [12]:
X[0]

array([[[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       ...,

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1.],
        [0., 0.

In [13]:
X[0][0]

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)

In [14]:
X[0][0][0]

array([0., 0., 0., 1.], dtype=float32)

In [38]:
model.compile(optimizer="adam", loss = "sparse_categorical_crossentropy", metrics = ["accuracy"])

In [39]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint 
earlystopping_cb = EarlyStopping(patience=20)
modelcheckpoint_cb = ModelCheckpoint("model.pkl", save_best_only=True)

In [40]:
model.fit(X, y, epochs = 100, validation_split=0.2, callbacks=[earlystopping_cb])

Train on 39200 samples, validate on 9800 samples
Epoch 1/100
39200/39200 [==============================] - 26s 673us/sample - loss: 0.1840 - accuracy: 0.9433 - val_loss: 0.0633 - val_accuracy: 0.9816
Epoch 2/100
39200/39200 [==============================] - 25s 647us/sample - loss: 0.0501 - accuracy: 0.9844 - val_loss: 0.0630 - val_accuracy: 0.9818
Epoch 3/100
39200/39200 [==============================] - 25s 645us/sample - loss: 0.0346 - accuracy: 0.9890 - val_loss: 0.0449 - val_accuracy: 0.9878
Epoch 4/100
39200/39200 [==============================] - 25s 648us/sample - loss: 0.0288 - accuracy: 0.9910 - val_loss: 0.0517 - val_accuracy: 0.9850
Epoch 5/100
39200/39200 [==============================] - 26s 652us/sample - loss: 0.0231 - accuracy: 0.9920 - val_loss: 0.0559 - val_accuracy: 0.9849
Epoch 6/100
39200/39200 [==============================] - 25s 650us/sample - loss: 0.0218 - accuracy: 0.9930 - val_loss: 0.0518 - val_accuracy: 0.9862
Epoch 7/100
39200/39200 [==============

In [19]:
model.save("model.pkl")

In [21]:
from tensorflow.keras.models import load_model
loaded_model = load_model("model.pkl")

In [33]:
# Uncomment to load images form test.csv
test = pd.read_csv("Test.csv")
#res = []
#t = []
#for i in test.filename:
#    t.append(image.imread("Images/test/"+i))
#    #res.app\end(np.argmax(model.predict(v)))

In [23]:
# Uncomment to dump test data
#f3 = open("test.pickle", "wb")
#pickle.dump(t, f3)
#f3.close()

In [24]:
f3 = open("test.pickle", "rb")
t = pickle.load(f3)

In [25]:
t = np.array(t)
res = loaded_model.predict(t)

In [26]:
len(res)

21000

In [27]:
r = []
for i in res:
    r.append(np.argmax(i))

In [28]:
len(r)

21000

In [29]:
print(r)

[4, 0, 9, 7, 9, 6, 6, 9, 0, 4, 2, 8, 4, 6, 1, 2, 9, 6, 1, 4, 0, 8, 4, 3, 7, 7, 5, 1, 6, 4, 7, 1, 2, 7, 1, 8, 0, 3, 2, 4, 3, 1, 8, 7, 7, 7, 3, 5, 0, 0, 2, 5, 6, 5, 1, 7, 2, 6, 7, 5, 9, 3, 9, 4, 3, 1, 6, 1, 2, 2, 1, 9, 3, 0, 2, 2, 1, 3, 5, 4, 7, 5, 4, 9, 8, 6, 6, 8, 6, 3, 5, 5, 5, 3, 6, 9, 7, 6, 9, 3, 9, 2, 4, 6, 2, 1, 3, 5, 1, 3, 2, 1, 1, 0, 5, 9, 4, 5, 2, 1, 5, 8, 9, 9, 9, 0, 6, 4, 8, 6, 3, 4, 5, 4, 6, 6, 6, 7, 2, 0, 1, 2, 8, 8, 2, 7, 0, 6, 2, 5, 8, 9, 6, 9, 8, 1, 1, 1, 8, 1, 0, 0, 5, 8, 6, 3, 4, 0, 4, 1, 7, 5, 7, 4, 2, 4, 1, 8, 1, 7, 1, 2, 0, 8, 0, 8, 5, 5, 0, 9, 9, 5, 9, 5, 6, 0, 4, 2, 1, 4, 3, 7, 2, 5, 1, 0, 7, 7, 1, 5, 8, 3, 2, 3, 8, 5, 3, 9, 4, 5, 3, 1, 2, 1, 0, 8, 0, 4, 0, 2, 5, 9, 9, 1, 7, 4, 4, 1, 0, 4, 3, 1, 3, 8, 9, 5, 6, 8, 0, 6, 2, 4, 3, 2, 8, 1, 6, 8, 1, 4, 9, 9, 6, 1, 4, 2, 4, 7, 4, 6, 8, 7, 3, 2, 4, 4, 7, 2, 6, 0, 8, 9, 4, 3, 3, 6, 3, 6, 6, 5, 1, 5, 0, 4, 5, 0, 8, 5, 1, 7, 8, 4, 4, 2, 6, 7, 2, 8, 5, 7, 9, 2, 3, 7, 2, 9, 1, 8, 5, 3, 7, 8, 5, 4, 0, 8, 6, 4, 7, 8, 1, 3, 2, 

In [30]:
s = pd.read_csv("sample_submission.csv")
s.head()

filename  label
0  49000.png      0
1  49001.png      0
2  49002.png      0
3  49003.png      0
4  49004.png      0

In [34]:
sub = pd.DataFrame({"filename":test.filename,"label":r})

In [35]:
sub.head()

filename  label
0  49000.png      4
1  49001.png      0
2  49002.png      9
3  49003.png      7
4  49004.png      9

In [36]:
sub.to_csv("sub989.csv",index=False)